version: "3.9"

services:
  db:
    image: postgres:15
    container_name: chat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # host:container

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chat_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chatdb
    ports:
      - "8001:8000"   # host:container

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chat_frontend
    depends_on:
      - backend
    ports:
      - "5174:80"     # host:container

volumes:
  pgdata:
